[ADD] Added member APIs
harunurkst/qard-al-hasana pull request #37
Opened 2023-03-26 15:13 UTC by rakibul-islam-raju

2023-03-26 15:14 UTC, rakibul-islam-raju commented
#15

2023-03-26 15:26 UTC, rakibul-islam-raju commented
#16

2023-03-27 05:15 UTC, harunurkst commented on backend/peoples/serializers.py
> +            "uuid",
uuid should be auto-generated,

2023-03-27 05:17 UTC, harunurkst commented on backend/peoples/serializers.py
> +            "branch",
branch value should be logged in staff's branch. No need to provide value from frontend.

2023-03-27 05:23 UTC, harunurkst requested changes
please resolve my feedback

2023-03-27 05:23 UTC, harunurkst commented on backend/peoples/serializers.py
> +            "branch",
branch value should be logged-in staff's branch.

2023-03-27 05:23 UTC, harunurkst commented on backend/peoples/views.py
> +    queryset = Member.objects.all()
show only logged-in staff's branch member

2023-03-27 10:17 UTC, rakibul-islam-raju commented
Thanks for your feedback! I've made the requested changes and pushed the updates to this PR. Please take another look and let me know if there's anything else that needs to be addressed.

2023-03-27 21:56 UTC, merged